i2c: a8k: unstuck when start clear bit timeouts
When performing back-to-back resets (~1s apart)
SPD I2C fails as the bus gets stuck:
ERROR:   Start clear bit timeout

Release the bus using the "unstuck" register.
This requires to soft-reset to complete successfully
(otherwise I2C drives to finish the requested start/stop
and interferes with unstuck FSM).

On successful completion of unstuck process reset i2c again.
The solution assumes failure occurs on the first access,
therefore -EAGAIN returned triggers a re-try and
SPD access is completed successfully:

NOTICE:  Gathering DRAM information
ERROR: Start clear bit timeout
Trying to "unstuck i2c"... ok
mv_ddr: version 16.12.1
mv_ddr: scrubbing memory...

Change-Id: I6a3a5ccb45edd0472de770ba55b747e6b6d357ff
Signed-off-by: Anton <antone@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/40573
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
Reviewed-by: Kostya Porotchkin <kostap@marvell.com>